# -*- coding: utf-8 -*-
"""MediVision-Ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjuQGuZL6vf4_zMuVJ1N-XQGqT3ADFb_

#Phase 3
"""

# --- Mount GDrive ---
from google.colab import drive
drive.mount('/content/drive')

!pip install opencv-python albumentations timm

# --- Libraries ---
import os
import cv2
import torch
import random
import numpy as np
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from torch.utils.data import DataLoader, Dataset
from torchvision import models,transforms
from torch import nn, optim

import albumentations as A
from albumentations.pytorch import ToTensorV2
from albumentations.augmentations.dropout import CoarseDropout
from timm import create_model

# --- Configuration ---
DATA_DIR = '/content/drive/My Drive/MLdatasets/Images'
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 15
SEED = 42
torch.manual_seed(SEED)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
classes = ['normal', 'benign', 'malignant']

def apply_clahe(img):
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0)
    cl = clahe.apply(l)
    limg = cv2.merge((cl, a, b))
    return cv2.cvtColor(limg, cv2.COLOR_LAB2RGB)

class BreastCancerDataset(Dataset):
    def __init__(self, img_paths, labels, transform=None, apply_clahe=False):
        self.img_paths = img_paths
        self.labels = labels
        self.transform = transform
        self.apply_clahe = apply_clahe

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img = cv2.imread(self.img_paths[idx])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        if self.apply_clahe:
            img = apply_clahe(img)
        if self.transform:
            img = self.transform(image=img)['image']
        return img, self.labels[idx]

def load_image_paths():
    all_paths, all_labels = [], []
    label_map = {cls: i for i, cls in enumerate(classes)}
    for cls in classes:
        folder = os.path.join(DATA_DIR, cls)
        for fname in os.listdir(folder):
            if fname.endswith(('jpg', 'png')):
                all_paths.append(os.path.join(folder, fname))
                all_labels.append(label_map[cls])
    return list(zip(all_paths, all_labels))

train_transform = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.ElasticTransform(p=0.3),
    A.GaussNoise(p=0.3),
    A.MotionBlur(p=0.2),
    A.RandomBrightnessContrast(p=0.4),
    CoarseDropout(max_holes=8, max_height=16, max_width=16, p=0.4),
    A.Normalize(mean=(0.5,), std=(0.5,)),
    ToTensorV2()
])

test_transform = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.Normalize(mean=(0.5,), std=(0.5,)),
    ToTensorV2()
])

def split_and_balance(data):
    class_data = {i: [] for i in range(len(classes))}
    for path, label in data:
        class_data[label].append((path, label))
    max_len = max(len(v) for v in class_data.values())

    balanced = []
    for label, items in class_data.items():
        items = items.copy()
        if len(items) < max_len:
            items += random.choices(items, k=max_len - len(items))
        balanced.extend(items)

    random.shuffle(balanced)
    total = len(balanced)
    train_len = int(0.7 * total)
    val_len = int(0.1 * total)

    train = balanced[:train_len]
    val = balanced[train_len:train_len + val_len]
    test = balanced[train_len + val_len:]
    return train, val, test

data = load_image_paths()
train_data, val_data, test_data = split_and_balance(data)

train_dataset = BreastCancerDataset([p for p, _ in train_data], [l for _, l in train_data],
                                    transform=train_transform, apply_clahe=True)
val_dataset = BreastCancerDataset([p for p, _ in val_data], [l for _, l in val_data],
                                  transform=test_transform, apply_clahe=True)
test_dataset = BreastCancerDataset([p for p, _ in test_data], [l for _, l in test_data],
                                   transform=test_transform, apply_clahe=False)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE)

# --- Hybrid Model (ResNet18 + ViT) ---
class HybridCNNViT(nn.Module):
    def __init__(self, num_classes=3):
        super(HybridCNNViT, self).__init__()
        self.cnn = models.resnet18(pretrained=True)
        self.cnn.fc = nn.Identity()

        self.vit = create_model('vit_base_patch16_224', pretrained=True)
        self.vit.head = nn.Identity()

        self.classifier = nn.Sequential(
            nn.Linear(512 + 768, 512),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )

    def forward(self, x):
        cnn_feat = self.cnn(x)
        vit_feat = self.vit(x)
        combined = torch.cat((cnn_feat, vit_feat), dim=1)
        return self.classifier(combined)

model = HybridCNNViT().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

def validate():
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for imgs, labels in val_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    print(f'Validation Accuracy: {100 * correct / total:.2f}%')

def train():
    for epoch in range(EPOCHS):
        model.train()
        running_loss = 0
        for imgs, labels in tqdm(train_loader):
            imgs, labels = imgs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(imgs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"Epoch {epoch+1}/{EPOCHS} - Loss: {running_loss/len(train_loader):.4f}")
        validate()

train()

def validate():
    model.eval()
    correct, total = 0, 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for imgs, labels in val_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    accuracy = 100 * correct / total
    print(f'Validation Accuracy: {accuracy:.2f}%')

    cm = confusion_matrix(all_labels, all_preds)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)

    disp.plot(cmap=plt.cm.Blues)
    plt.title("Confusion Matrix")
    plt.show()

# --- Load Model ---
model = HybridCNNViT()
model.load_state_dict(torch.load('/content/drive/My Drive/hybrid_model.pth', map_location=device))
model.to(device).eval()

# --- Image Preprocessing ---
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5,), std=(0.5,))
])

def predict_image(image_path):
    image = Image.open(image_path).convert('RGB')
    image_tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(image_tensor)
        _, predicted = torch.max(outputs, 1)
        return classes[predicted.item()]

img_path = '/content/drive/My Drive/MLdatasets/Images/benign/benign (100).png'
prediction = predict_image(img_path)
print("Predicted class:", prediction)

"""Q1"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

def validate():
    model.eval()
    correct, total = 0, 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for imgs, labels in val_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    accuracy = 100 * correct / total
    print(f'Validation Accuracy: {accuracy:.2f}%')

    cm = confusion_matrix(all_labels, all_preds)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)

    disp.plot(cmap=plt.cm.Blues)
    plt.title("Confusion Matrix")
    plt.show()

def train():
    for epoch in range(EPOCHS):
        model.train()
        running_loss = 0
        for imgs, labels in tqdm(train_loader):
            imgs, labels = imgs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(imgs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        print(f"Epoch {epoch+1}/{EPOCHS} - Loss: {running_loss/len(train_loader):.4f}")
        validate()

train()

"""Q2

#Phase 2
"""

drive.mount('/content/drive')
dataset_path = "/content/drive/My Drive/MLdatasets/Images"

#Verify subfolder
categories = ["benign", "malignant", "normal"]
for category in categories:
    print(f"Checking folder: {category}")
    print(os.listdir(os.path.join(dataset_path, category))[:2])

def remove_mask_img(dataset_path, categories):
    for category in categories:
        mask_img = glob.glob(os.path.join(dataset_path, category, "*_mask.png"))
        print(f"Removing {len(mask_img)} mask images in {category}...")

        for mask_img in mask_img:
            os.remove(mask_img)

remove_mask_img(dataset_path, categories)

def add_gaussian_noise(image, mean=0, std=25):
    noise = np.random.normal(mean, std, image.shape).astype(np.float32)
    return np.clip(image.astype(np.float32) + noise, 0, 255).astype(np.uint8)

def elastic_transform(image, alpha=34, sigma=4):
    random_state = np.random.RandomState(None)
    shape = image.shape
    dx = cv2.GaussianBlur((random_state.rand(*shape[:2]) * 2 - 1), (17, 17), sigma) * alpha
    dy = cv2.GaussianBlur((random_state.rand(*shape[:2]) * 2 - 1), (17, 17), sigma) * alpha
    x, y = np.meshgrid(np.arange(shape[1]), np.arange(shape[0]))
    map_x = (x + dx).astype(np.float32)
    map_y = (y + dy).astype(np.float32)
    return cv2.remap(image, map_x, map_y, interpolation=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT)

def apply_clahe(img):
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0)
    cl = clahe.apply(l)
    limg = cv2.merge((cl, a, b))
    return cv2.cvtColor(limg, cv2.COLOR_LAB2RGB)

def enhance_image_pipeline(image):
    image = apply_clahe(image)
    image = elastic_transform(image)
    image = add_gaussian_noise(image)
    return image

def create_enhanced_dataset(src_path, dest_path):
    if os.path.exists(dest_path):
        shutil.rmtree(dest_path)
    os.makedirs(dest_path)

    for category in categories:
        src_category_path = os.path.join(src_path, category)
        dest_category_path = os.path.join(dest_path, category)
        os.makedirs(dest_category_path, exist_ok=True)

        for img_name in os.listdir(src_category_path):
            img_path = os.path.join(src_category_path, img_name)
            image = Image.open(img_path).convert("RGB").resize((224, 224))
            image_np = np.array(image)

            enhanced_img = enhance_image_pipeline(image_np)
            enhanced_img_pil = Image.fromarray(enhanced_img)
            enhanced_img_pil.save(os.path.join(dest_category_path, img_name))

create_enhanced_dataset(original_path, enhanced_path)

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

"""Load Enhanced Dataset & Build Model"""

data_gen = ImageDataGenerator(rescale=1./255, rotation_range=20, zoom_range=0.15, width_shift_range=0.2, height_shift_range=0.2, horizontal_flip=True, fill_mode='nearest', validation_split=0.2)

sample_path = os.path.join(original_path, 'benign')
sample_img_name = os.listdir(sample_path)[0]
sample_img_path = os.path.join(sample_path, sample_img_name)

original_image = Image.open(sample_img_path).convert("RGB").resize((224, 224))
original_np = np.array(original_image)

clahe_img = apply_clahe(original_np)
elastic_img = elastic_transform(clahe_img)
gaussian_img = add_gaussian_noise(elastic_img)

plt.figure(figsize=(12, 4))

plt.subplot(1, 4, 1)
plt.imshow(original_np)
plt.title("Original")
plt.axis('off')

plt.subplot(1, 4, 2)
plt.imshow(clahe_img)
plt.title("CLAHE")
plt.axis('off')

plt.subplot(1, 4, 3)
plt.imshow(elastic_img)
plt.title("Elastic Transform")
plt.axis('off')

plt.subplot(1, 4, 4)
plt.imshow(gaussian_img)
plt.title("Gaussian Noise")
plt.axis('off')

plt.tight_layout()
plt.show()

train_generator = data_gen.flow_from_directory(enhanced_path, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical", subset="training")

val_generator = data_gen.flow_from_directory(enhanced_path, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical", subset="validation")

class ViTLayer(tf.keras.layers.Layer):
    def __init__(self, model_name="google/vit-base-patch16-224"):
        super(ViTLayer, self).__init__()
        self.vit_model = TFAutoModel.from_pretrained(model_name)

    def call(self, inputs):
        transformer_features = self.vit_model(inputs, training=False).last_hidden_state
        return tf.reduce_mean(transformer_features, axis=1)

"""CNN + ViT Combined Model"""

shared_input = Input(shape=(224, 224, 3), name="shared_input")

# Vision Transformer Layer
vit_input = shared_input
transformed_input = Permute((3, 1, 2))(vit_input)
transformer_output = ViTLayer()(transformed_input)

input_layer = Input(shape=(224, 224, 3), name='hybrid_input')

# ResNet-style block
x1 = Conv2D(64, (7, 7), strides=(2, 2), padding='same', name='res_block1_conv')(input_layer)
x1 = BatchNormalization()(x2)
x1 = ReLU()(x2)
x1 = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), padding='same')(x2)
x1 = GlobalAveragePooling2D()(x2)

trans_input = GlobalAveragePooling2D()(input_layer)
transformer_output = Dense(768, activation='relu', name='transformer_output')(trans_input)
merged = Concatenate()([x2, transformer_output])

dense1 = Dense(256, activation='relu')(merged)
drop1 = Dropout(0.5)(dense1)
output = Dense(3, activation='softmax')(drop1)

#Model
model = Model(inputs=input_layer, outputs=output)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

#Model Compile
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
model.compile(
    optimizer=optimizer,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=1)

def lr_schedule(epoch, lr):
    if epoch < 5:
        return lr
    elif epoch < 10:
        return lr * 0.5
    else:
        return lr * 0.1

lr_scheduler = tf.keras.callbacks.LearningRateScheduler(lr_schedule, verbose=1)

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=20,
    callbacks=[early_stop, reduce_lr, lr_scheduler]
)

# Plot training & validation accuracy values
plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Accuracy-Train', marker='o')
plt.plot(history.history['val_accuracy'], label='Accuracy-Validation', marker='x')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Loss-Train', marker='o')
plt.plot(history.history['val_loss'], label='Loss-Validation', marker='x')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# ----- Test + Confusion Matrix + Per-Class Accuracy -----
def test_and_evaluate():
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for imgs, labels in test_loader:
            imgs = imgs.to(device)
            outputs = model(imgs)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.numpy())

    cm = confusion_matrix(all_labels, all_preds)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)
    disp.plot(cmap='Blues')
    plt.title('Confusion Matrix')
    plt.show()

    # ---- Per-Class Accuracy ----
    print("\nAccuracy Per-Class:")
    class_accuracies = {}
    for i, class_name in enumerate(classes):
        correct = cm[i, i]
        total = cm[i].sum()
        accuracy = 100 * correct / total if total > 0 else 0
        class_accuracies[class_name] = accuracy
        print(f"{class_name}: {accuracy:.2f}%")


    print("\nClassification Report:")
    print(classification_report(all_labels, all_preds, target_names=classes))

test_and_evaluate()

""" ## Phase 1"""

from google.colab import drive
import os
import glob
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import Sequence
import tensorflow as tf
from transformers import TFAutoModel
from tensorflow.keras.layers import Dense, Flatten, Concatenate, Input, Permute
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

#Models
from tensorflow.keras.applications import ResNet50, MobileNetV2, EfficientNetB0, DenseNet121, InceptionV3

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

data_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

train_gen = data_gen.flow_from_directory(
    dataset_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training"
)

val_gen = data_gen.flow_from_directory(
    dataset_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation"
)

"""Define the Hybrid CNN-Transformer Model

RESNET
"""

class ViTLayer(tf.keras.layers.Layer):
    def __init__(self, model_name="google/vit-base-patch16-224"):
        super(ViTLayer, self).__init__()
        self.vit_model = TFAutoModel.from_pretrained(model_name)

    def call(self, inputs):
        transformer_features = self.vit_model(inputs, training=False).last_hidden_state
        return tf.reduce_mean(transformer_features, axis=1)

#ResNet50 Feature Extractor
res_base = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
cnn_output = Flatten()(res_base.output)

transformer_input = Input(shape=(224, 224, 3), name="vit_input")
transformed_input = Permute((3, 1, 2))(transformer_input)

transformer_output = ViTLayer()(transformed_input)

merged = Concatenate()([cnn_output, transformer_output])
final_output = Dense(3, activation='softmax')(merged)
model_res = Model(inputs=[res_base.input, transformer_input], outputs=final_output)

model_res.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model_res.summary()

"""Train & Evaluate the Model"""

class DualInputDataGen(Sequence):
    def __init__(self, generator):
        self.generator = generator

    def __len__(self):
        return len(self.generator)

    def __getitem__(self, index):
        images, labels = self.generator[index]
        return (images, images), labels

train_gen_dual = DualInputDataGen(train_gen)
val_gen_dual = DualInputDataGen(val_gen)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6)
]

history = model_res.fit(
    train_gen_dual,
    validation_data=val_gen_dual,
    epochs=10,
    callbacks=callbacks
)

"""Evaluate Model Performance"""

def plot_metrics(history):
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Accuracy-Train')
    plt.plot(history.history['val_accuracy'], label='Accuracy-Validation')
    plt.title('ResNet50+ViT Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Loss-Train')
    plt.plot(history.history['val_loss'], label='Loss-Validation')
    plt.title('ResNet50+ViT Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

plot_metrics(history)

"""EfficientNetB0"""

class ViTLayer(tf.keras.layers.Layer):
    def __init__(self, model_name="google/vit-base-patch16-224"):
        super(ViTLayer, self).__init__()
        self.vit_model = TFAutoModel.from_pretrained(model_name)

    def call(self, inputs):
        transformer_features = self.vit_model(inputs, training=False).last_hidden_state
        return tf.reduce_mean(transformer_features, axis=1)

#EfficientNetB0 Feature Extractor
effi_base = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
cnn_output = Flatten()(effi_base.output)

transformer_input = Input(shape=(224, 224, 3), name="vit_input")
transformed_input = Permute((3, 1, 2))(transformer_input)


transformer_output = ViTLayer()(transformed_input)

merged = Concatenate()([cnn_output, transformer_output])

final_output = Dense(3, activation='softmax')(merged)

model_effi = Model(inputs=[effi_base.input, transformer_input], outputs=final_output)

model_effi.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
                           loss='categorical_crossentropy',
                           metrics=['accuracy'])

model_effi.summary()

class DualInputDataGen(Sequence):
    def __init__(self, generator):
        self.generator = generator

    def __len__(self):
        return len(self.generator)

    def __getitem__(self, index):
        images, labels = self.generator[index]
        return (images, images), labels

train_gen_dual = DualInputDataGen(train_gen)
val_gen_dual = DualInputDataGen(val_gen)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6)
]

history = model_effi.fit(
    train_gen_dual,
    validation_data=val_gen_dual,
    epochs=10,
    callbacks=callbacks
)

def plot_metrics(history):
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Accuracy-Train')
    plt.plot(history.history['val_accuracy'], label='Accuracy-Validation')
    plt.title('EffiB0+ViT Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Loss-Train')
    plt.plot(history.history['val_loss'], label='Loss-Validation')
    plt.title('EffiB0+ViT Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

plot_metrics(history)

"""DenseNet121"""

class ViTLayer(tf.keras.layers.Layer):
    def __init__(self, model_name="google/vit-base-patch16-224"):
        super(ViTLayer, self).__init__()
        self.vit_model = TFAutoModel.from_pretrained(model_name)

    def call(self, inputs):
        transformer_features = self.vit_model(inputs, training=False).last_hidden_state
        return tf.reduce_mean(transformer_features, axis=1)

#DenseNet121 Feature Extractor
den_base = DenseNet121(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
cnn_output = Flatten()(den_base.output)

transformer_input = Input(shape=(224, 224, 3), name="vit_input")
transformed_input = Permute((3, 1, 2))(transformer_input)

transformer_output = ViTLayer()(transformed_input)

merged = Concatenate()([cnn_output, transformer_output])

final_output = Dense(3, activation='softmax')(merged)

model_den = Model(inputs=[den_base.input, transformer_input], outputs=final_output)

model_den.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
                       loss='categorical_crossentropy',
                       metrics=['accuracy'])

model_den.summary()

class DualInputDataGen(Sequence):
    def __init__(self, generator):
        self.generator = generator

    def __len__(self):
        return len(self.generator)

    def __getitem__(self, index):
        images, labels = self.generator[index]
        return (images, images), labels

train_gen_dual = DualInputDataGen(train_generator)
val_gen_dual = DualInputDataGen(val_generator)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6)
]

history = model_den.fit(
    train_gen_dual,
    validation_data=val_gen_dual,
    epochs=10,
    callbacks=callbacks
)

def plot_metrics(history):
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Accuracy-Train')
    plt.plot(history.history['val_accuracy'], label='Accuracy-Validation')
    plt.title('Den+ViT Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Loss-Train')
    plt.plot(history.history['val_loss'], label='Loss-Validation')
    plt.title('Den+ViT Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

plot_metrics(history)

"""InceptionV3"""

class ViTLayer(tf.keras.layers.Layer):
    def __init__(self, model_name="google/vit-base-patch16-224"):
        super(ViTLayer, self).__init__()
        self.vit_model = TFAutoModel.from_pretrained(model_name)

    def call(self, inputs):
        transformer_features = self.vit_model(inputs, training=False).last_hidden_state
        return tf.reduce_mean(transformer_features, axis=1)

#InceptionV3 Feature Extractor
incep_base = InceptionV3(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
incep_output = Flatten()(incep_base.output)

transformer_input = Input(shape=(224, 224, 3), name="vit_input")
transformed_input = Permute((3, 1, 2))(transformer_input)

transformer_output = ViTLayer()(transformed_input)

merged = Concatenate()([incep_output, transformer_output])

final_output = Dense(3, activation='softmax')(merged)

model_incep = Model(inputs=[incep_base.input, transformer_input], outputs=final_output)

model_incep.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
                        loss='categorical_crossentropy',
                        metrics=['accuracy'])

model_incep.summary()

class DualInputDataGen(Sequence):
    def __init__(self, generator):
        self.generator = generator

    def __len__(self):
        return len(self.generator)

    def __getitem__(self, index):
        images, labels = self.generator[index]
        return (images, images), labels

train_gen_dual = DualInputDataGen(train_generator)
val_gen_dual = DualInputDataGen(val_generator)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6)
]

history = model_incep.fit(
    train_gen_dual,
    validation_data=val_gen_dual,
    epochs=10,
    callbacks=callbacks
)

def plot_metrics(history):
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Accuracy-Train')
    plt.plot(history.history['val_accuracy'], label='Accuracy-Validation')
    plt.title('IncepV3+ViT Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Loss-Train')
    plt.plot(history.history['val_loss'], label='Loss-Validation')
    plt.title('IncepV3+ViT Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

plot_metrics(history)

"""MobileNetV2"""

class ViTLayer(tf.keras.layers.Layer):
    def __init__(self, model_name="google/vit-base-patch16-224"):
        super(ViTLayer, self).__init__()
        self.vit_model = TFAutoModel.from_pretrained(model_name)

    def call(self, inputs):
        transformer_features = self.vit_model(inputs, training=False).last_hidden_state
        return tf.reduce_mean(transformer_features, axis=1)

#MobileNetV2 Feature Extractor
mob_base = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
mob_output = Flatten()(mob_base.output)

transformer_input = Input(shape=(224, 224, 3), name="vit_input")
transformed_input = Permute((3, 1, 2))(transformer_input)

transformer_output = ViTLayer()(transformed_input)

#Merge CNN + Transformer Outputs
merged = Concatenate()([mob_output, transformer_output])
final_output = Dense(3, activation='softmax')(merged)
model_mob = Model(inputs=[mob_base.input, transformer_input], outputs=final_output)

#Model Compile
model_mob.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model_mob.summary()

class DualInputDataGen(Sequence):
    def __init__(self, generator):
        self.generator = generator

    def __len__(self):
        return len(self.generator)

    def __getitem__(self, index):
        images, labels = self.generator[index]
        return (images, images), labels

train_gen_dual = DualInputDataGen(train_gen)
val_gen_dual = DualInputDataGen(val_gen)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6)
]

history = model_mob.fit(
    train_gen_dual,
    validation_data=val_gen_dual,
    epochs=10,
    callbacks=callbacks
)

def plot_metrics(history):
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Accuracy-Train')
    plt.plot(history.history['val_accuracy'], label='Accuracy-Validation')
    plt.title('Mob+ViT Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Loss-Train')
    plt.plot(history.history['val_loss'], label='Loss-Validation')
    plt.title('Mob+ViT Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

plot_metrics(history)